version: '3'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: python-api
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: my-postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - database:/var/lib/postgresql/data/pgdata
  
  web:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/usr/srv/app:rw
    environment:
      DATABASE_URL: "postgresql+psycopg://postgres-user:my-postgres@db:5432/python-api"

volumes:
  database: